# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c9a13788-7067-4c4e-9f47-145d9e98bd66";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/46F3-DA4A";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4012d614-ae23-490d-8d80-8daaab15f04d";
      fsType = "ext4";
    };

  fileSystems."/home/Media" =
    { device = "/dev/disk/by-uuid/6a39be48-c0da-4b9d-b9d4-dd1f1398f087";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/07eafb78-1f2c-4054-9ec0-a936245ddd73"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
