ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.conkyrc ~/.conkyrc
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.gitexcludes ~/.gitexcludes
ln -s ~/dotfiles/.gvimrc ~/.gvimrc
ln -s ~/dotfiles/.hgrc ~/.hgrc
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.vim ~/.vim
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.emacs ~/.emacs
ln -s ~/dotfiles/.viper ~/.viper
ln -s ~/dotfiles/bin ~/bin
ln -s ~/dotfiles/.xmonad ~/.xmonad
ln -s ~/dotfiles/.Xresources ~/.Xresources
ln -s ~/dotfiles/.yi ~/.yi
